default:
  prefix: "raw"
  schema: "dev"
  bucket: "bgg_data_dev"
  project_id: "gcp-demos-411520"
  batch_size: 20
  workers: 4
  log_level: "DEBUG"
  
staging:
  prefix: "raw"
  schema: "staging"
  bucket: "bgg_data_staging"
  project_id: "gcp-demos-411520"
  batch_size: 20
  workers: 4
  log_level: "INFO"
  
production:
  prefix: "raw"
  schema: "raw"
  bucket: "bgg_data"
  project_id: "gcp-demos-411520"
  batch_size: 20
  workers: 4
  log_level: "WARN"
