name: Push to GCR GitHub Action
on: 
  push:
  pull_request:
    branches:
      - main
jobs:
  build-and-push-to-gcr-service-account:
    name: Build & push - with service account
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCS_AUTH_FILE }}'
      - name: Building and pushing the image
        uses: ./
        # uses: RafikFarhad/push-to-gcr-github-action@v5-rc1 # <- use this on your workflow
        with:
          registry: gcr.io
          project_id: gcp-demos-411520
          image_name: bgg_data
          image_tag: test
          dockerfile: Dockerfile
          context: .
          target: build