run-name: ${{ github.actor }} is fiddling with renv
on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev, main]

name: renv-restore
    
jobs:
  renv-restore:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-renv@v2
