run-name: ${{ github.actor }} is updating the README
on:
  schedule:
    - cron: '0 1 * * *'
  push:
    branches: [dev, main]

name: renv
    
jobs:
  renv-restore:
    runs-on: ubuntu-latest
    env: 
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      GCS_AUTH_FILE: ${{ secrets.GCS_AUTH_FILE }}
      GCS_AUTH_KEY: ${{ secrets.GCS_AUTH_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - uses: r-lib/actions/setup-pandoc@v2
      
      - name: Install Linux system dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install libcurl4-openssl-dev
          sudo apt-get install libssl-dev
          sudo apt-get install libzmq3-dev
          sudo apt-get install libxml2-dev 
          sudo apt-get install libglpk-dev 
          sudo apt-get install libsodium-dev 
      - uses: r-lib/actions/setup-renv@v2
      - name: Check status of targets
        shell: Rscript {0}
        run: |
          renv::activate()
          targets::tar_meta()
      - name: Render README
        shell: Rscript {0}
        run: |
          renv::activate()
          rmarkdown::render("README.Rmd")
      - name: commit README
        run: |
          git config --global user.name ${{ github.actor }}
          git commit README.md -m 'Re-build README.Rmd' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
