run-name: ${{ github.actor }} is fiddling with renv
on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev, main]

name: renv
    
jobs:
  renv-restore:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - uses: r-lib/actions/setup-pandoc@v2
      
      - name: Install linux system dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install libcurl4-openssl-dev
          sudo apt-get install libssl-dev
          sudo apt-get install libzmq3-dev
          sudo apt-get install libxml2-dev 
          sudo apt-get install libglpk-dev 
          sudo apt-get install libsodium-dev 
      - uses: r-lib/actions/setup-renv@v2
